### ISSUE TITLE
Game wont load

### ISSUE THREAD

**Issue by s0meoneyoukn0w** [MentatMinions/IndustriaArcanum#101]
crash report:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/12/15 10:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/ExplosionEvent
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/ExplosionEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60)
	at com.vikestep.sprinklesforvanilla.CommonProxy.registerHandler(CommonProxy.java:19)
	at com.vikestep.sprinklesforvanilla.CommonProxy.init(CommonProxy.java:49)
	at com.vikestep.sprinklesforvanilla.ClientProxy.init(ClientProxy.java:12)
	at com.vikestep.sprinklesforvanilla.SprinklesForVanilla.init(SprinklesForVanilla.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.world.ExplosionEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 462504448 bytes (441 MB) / 1038876672 bytes (990 MB) up to 8018198528 bytes (7646 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms1024M -Xmx7680M -XX:PermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 101 mods loaded, 101 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.6.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AgriCraft{1.7.10-1.2.2} [AgriCraft] (AgriCraft-1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	aura{0.1r0} [Aura Cascade] (AuraCasade-201.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Automagy{0.19.3} [Automagy] (Automagy-1.7.10-0.19.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized
	autopackager{1.5.2} [AutoPackager] (autopackager-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Botania{r1.4-158} [Botania] (Botania r1.4-158.jar) Unloaded->Constructed->Pre-initialized->Initialized
	buildhelper{1.0.0} [Build Helper] (BuildHelper_v1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMultipart{1.1.1.321} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	chisel{2.3.5.31} [Chisel 2] (Chisel2-2.3.5.31.jar) Unloaded->Constructed->Pre-initialized->Initialized
	clockworkphase{1.7.10_1.0c} [Clockwork Phase] (clockworkphase-1.7.10_1.0c.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DescriptionTags{1.0} [Description Tags] (DescriptionTags-1.0-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	OmnisCore{0.0.5} [Omnis Core] (OmnisCore-0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	dimensionalPockets{0.10.4} [Dimensional Pockets] (dimensionalPockets-0.10.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	EnderIO{1.7.10-2.2.8.344} [Ender IO] (EnderIO-1.7.10-2.2.8.344.jar) Unloaded->Constructed->Pre-initialized->Initialized
	EnderZoo{1.7.10-1.0.7.16} [Ender Zoo] (EnderZoo-1.7.10-1.0.7.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Steamcraft{0.27.4} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.27.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ttCore{MC1.7.10-0.1.0-65} [ttCore] (ttCore-MC1.7.10-0.1.0-65.jar) Unloaded->Constructed->Pre-initialized->Initialized
	fluxedcrystals{0.0.4} [Fluxed-Crystals] (fluxedCrystals-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForbiddenMagic{1.7.10-0.552} [Forbidden Magic] (Forbidden Magic-1.7.10-0.552.jar) Unloaded->Constructed->Pre-initialized->Initialized
	McMultipart{1.1.1.321} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GardenCore{1.2.3} [Garden Core] (GardenStuff-1.7.10-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GardenContainers{1.2.2} [Garden Containers] (GardenStuff-1.7.10-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GardenTrees{1.2.2} [Garden Trees] (GardenStuff-1.7.10-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	headcrumbs{1.3.0} [Headcrumbs] (Headcrumbs-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded->Constructed->Pre-initialized->Initialized
	ImmibisCore{59.0.7} [Immibis Core] (immibis-core-59.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	InGameInfoXML{2.8.1.73} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	simplyjetpacks{1.3.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	InGameInfoXML|simplyjetpacksIntegration{2.8.1.73} [InGame Info XML - Simply Jetpacks Integration] (InGameInfoXML-1.7.10-2.8.1.73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	InGameInfoXML|ThaumcraftIntegration{2.8.1.73} [InGame Info XML - Thaumcraft Integration] (InGameInfoXML-1.7.10-2.8.1.73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inpure|core{1.7.10R1.0.0B8} [INpureCore] (INpureCore-[1.7.10]1.0.0B8-49.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	jacb{1.0.0} [JACB] (JACB-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_FairPlay_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	LLadders{0.5.0} [Luppii's Ladders] (Ladders-0.5.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	nolpfij_mobstatues{0.1.0} [mobstatues] (MobStatues-1.7.10-0.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized
	MyWorldGen{1.3.6} [MyWorldGen] (MyWorldGen-1.7.10-1.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	neiintegration{1.0.6} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized
	neresources{0.1.0.83} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.83.jar) Unloaded->Constructed->Pre-initialized->Initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized
	progressiveautomation{1.5.18} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.5.18.jar) Unloaded->Constructed->Pre-initialized->Initialized
	PvpToggle{1.7.10-0.1.14} [PVP Toggle] (pvpToggle-1.7.10-0.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	quiverchevsky{b87} [QuiverBow] (QuiverBow_1.7.10_b87.zip) Unloaded->Constructed->Pre-initialized->Initialized
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RefinedRelocation{1.0.7d} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.7d.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ServerTools{1.7.10-2.3.0.1} [ServerTools] (ServerTools-CORE-1.7.10-2.3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SimpleLantern{1.0} [Simple Lantern] (SimpleLantern-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	sprinkles_for_vanilla{1.1.1} [sprinkles_for_vanilla] (sprinklesforvanilla-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Errored
	StorageDrawers{1.2.0} [Storage Drawers] (StorageDrawers-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	tcnodetracker{1.0.1} [TC Node Tracker] (tcnodetracker-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	thaumicinfusion{3.8.1} [Thaumic Infusion] (ThaumicInfusion-1.7.10-3.83.jar) Unloaded->Constructed->Pre-initialized->Initialized
	TooMuchRain{%VERSION%} [TooMuchRain] (TooMuchRain-1.7.2-1.0.0-b5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wailaplugins{MC1.7.10-0.0.1-13} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wawla{1.1.1} [What Are We Looking At] (Wawla-1.1.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	aobd{2.3.6} [Another One Bites The Dust] (AOBD-2.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FMPIntegration{1.0} [FMPIntegration] (fmpintegration-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMicroblock{1.1.1.321} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	HungerOverhaul{1.7.10-beta.4.jenkins44} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	zzzzzcustomconfigs{2.1.0} [ZZZZZ Custom Configs] (ZZZZZ Custom Configs-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Mantle Environment: Environment healthy.

**Comment by s0meoneyoukn0w** [comment]
the console also had this:
[12/2/2015 22:32:40 PM] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[12/2/2015 22:32:40 PM] [Client thread/ERROR] [FML]: Caught exception from sprinkles_for_vanilla
[12/2/2015 22:32:40 PM] java.lang.NoClassDefFoundError: net/minecraftforge/event/world/ExplosionEvent

**Comment by Saphrym** [comment]
Do a fresh install.

**Comment by s0meoneyoukn0w** [comment]
i tried that aswell

**Comment by Saphrym** [comment]
Works for everyone else. Seems you're having conflicts with two mods that shouldn't be installed at the same time.

**Comment by VikeStep** [comment]
This is an error with my mod and it's because he is using an outdated forge, my mod requires at least Forge xx72

**Comment by Saphrym** [comment]
Ack.I didn't even notice the "errored" part. Sorry Shaun! 

Thank you very much VikeStep for letting me know. And your mod is awesome!
