### ISSUE TITLE
Fix Jungle Saplings

### ISSUE THREAD

**Issue by BarlockJKD** [MentatMinions/IndustriaArcanum#102]
Fishing seems to be fine both with a vanilla rod, and an enchanted vanilla rods. No issues. 
Farming; The reaping of crops is way too high ending up with too many seeds. Results show more seeds per plant reap then crop. this needs adjusting. 
Craft table; needs to add script to keep item in craft table. Reason: Pam's large recipes, if you for get an item and have to close the craft table ingredients spew all over the place and you have to reset the entire recipe.
Jungle saps still not producing off of leaves like they should. Getting 0-1 per entire tree.

**Comment by Saphrym** [comment]
Edited seed drops.
Already added crafting table mod.
Working on jungle saps.

**Comment by Saphrym** [comment]
MAde a recipe to convert jungle leaves directly to saplings.
