### ISSUE TITLE
Rehosting of mods

### ISSUE THREAD

**Issue by VikeStep** [MentatMinions/IndustriaArcanum#105]
Hello, I hate to be pedantic but I noticed that you rehost every mod in the mods folder here. There are countless mods there that forbid rehosting like this so I'd strongly advise removing it and creating a .gitignore file that makes it so that the mods aren't uploaded to github.

I'm personally not fussed for my mod, but for others it is against their license to do so.

**Comment by Saphrym** [comment]
Hmmmm. I'm new to Github... but this is the way I've seen every pack (Such as Running Red, Crash Landing, etc.) that is on Github do the development of the pack.

Is there a better way to do this then? I have to be able to provide the pack to my fellow developers.

**Comment by VikeStep** [comment]
Hmm... I'm going to contact Gideon as I don't think standard modpack permissions allow for this unless he asked for special permissions to do so. I'll get back to you once I have contacted him

**Comment by VikeStep** [comment]
As an example of a mod which I believe this violates a license of is JourneyMap which has given strict modpack permissions to mods on the FTB Launcher, whereas this is hosting it on Github. Similarly, Railcraft might also not be within license.

My suggestions to alternatives to rehosting mods:
1. Use a private bitbucket (which is free) and add those who you want to be able to download development versions to be able to view it
2. Provide links to updated mods in a text file so people can manually update to development versions of the pack
3. Send it to people privately

Of course, you could continue without doing it, but in case some mod dev stumbles on this and doesn't like it they may request you to take it down. So yeah, im not forcing you to take it down, but just to think about it.

**Comment by VikeStep** [comment]
It seems that gideon said that he assumed modpack permissions implied github permissions but would take down the individual mods if any wished for it down. So you can close this and continue as normal. Sorry for the hassle

**Comment by Saphrym** [comment]
Thanks much for letting me know! Again... I'm still new to modpack making. ;)
