### ISSUE TITLE
Fluxed crystals

### ISSUE THREAD

**Issue by s0meoneyoukn0w** [MentatMinions/IndustriaArcanum#106]
dont click the infuse button on the seed infuser while there is a seed already finished in the infuser it allows you to say goodbye server

**Comment by itanshi** [comment]
https://github.com/jaredlll08/Fluxed-Crystals/issues Not sure I see that this was reported before

**Comment by Saphrym** [comment]
I'll remove Fluxed Crystals. :(

**Comment by s0meoneyoukn0w** [comment]
but then what are we gonna do for rescource gen? atleast add in funky loco so i can make a frame quarry out of an arcane bore

**Comment by Saphrym** [comment]
There are tons of resource options. And no funky locomotion. It's not a server friendly.
