### ISSUE TITLE
cant connect to server

### ISSUE THREAD

**Issue by s0meoneyoukn0w** [MentatMinions/IndustriaArcanum#110]
![image](https://cloud.githubusercontent.com/assets/9582049/6198427/567c1830-b454-11e4-8bb5-0d367355d795.png)

and it just comes up with timed out each time i try to connect even thoughi have refreshed it it still says i can connect but when i try connecting it times me out

**Comment by Saphrym** [comment]
Restarting. Try again. And do you have Skype?

**Comment by s0meoneyoukn0w** [comment]
i have had bad experience with windows 8 and skype

**Comment by Saphrym** [comment]
ok
