### ISSUE TITLE
[suggestion] Quiverbow

### ISSUE THREAD

**Issue by someguyfromdownthestreet** [MentatMinions/IndustriaArcanum#54]
http://www.curse.com/mc-mods/minecraft/quiverbow

this seems fun you might want to remove/change some recipes

**Comment by itanshi** [comment]
Rocket launchers and cross bows? Eh, I play with it, but I'm not sure we need it. We have long bows.

**Comment by Saphrym** [comment]
Agreed. It was on the list at the beginning.... but removed when we got the newest version of TiC and after I noticed the rocket launchers. :P A different kind of pack would be great for this.
