### ISSUE TITLE
More pistons

### ISSUE THREAD

**Issue by someguyfromdownthestreet** [MentatMinions/IndustriaArcanum#57]
i remember this mod its really fun and it might give me a reason to do redstone

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288960-more-pistons-2-0-0-beta-and-1-5-0-build-by-smeagol

**Comment by itanshi** [comment]
Amusing, I'd like project red integration or similar

**Comment by Saphrym** [comment]
Interesting. I'll think about it.

Also... we have Project Red in IA now. Not the pipes or the world gen.... but the redstone circuits and such.

**Comment by itanshi** [comment]
sounds good
