### ISSUE TITLE
Backpack melon juice crashes.

### ISSUE THREAD

**Issue by Saphrym** [MentatMinions/IndustriaArcanum#63]

**Comment by itanshi** [comment]
https://github.com/Darkona/AdventureBackpack2/issues/32

**Comment by Saphrym** [comment]
Need to validate that it happens without Modular Systems.

**Comment by OrionDevelopment** [comment]
Fixed in the lattest release!

**Comment by Saphrym** [comment]
Still happening.

**Comment by OrionDevelopment** [comment]
Will check it again!

**Comment by Saphrym** [comment]
"Remove recipes for melon juice and Melon backpack"

**Comment by OrionDevelopment** [comment]
Probably for the best yes,

I had the crash now too. Could not figure out why it did not crash the first time though…

 

Maybe it depends on the order we do stuff or if it is a creative spawned one or not?
