### ISSUE TITLE
Copper and Tin ore have 2 ingot types

### ISSUE THREAD

**Issue by itanshi** [MentatMinions/IndustriaArcanum#67]
If I create dust using the modular ore processor with copper or tin, it produces apple milk tea dust. If I cook this dust in the modular furnace its one type of ingot, if I cook with alloy smelter, its another. If I sag an ingot and smelt it in the modular furnace it's the same ingot the alloy smelter makes.

**Comment by Saphrym** [comment]
We'll reopen this if the problem continues without Modular Systems.
