### ISSUE TITLE
Tinker's Smeltery has many incorrect recipes

### ISSUE THREAD

**Issue by itanshi** [MentatMinions/IndustriaArcanum#68]
So as a byproduct of sag mill, iron produces ferrous which can be cooked into iron. This might be an ok default behavior. If you smelt the dust in tinkers you get lead, if you combine lead and gold you get electrum if you pour electrum into a bucket you get [invar] lead.

I can smelt cobble into emerald, make steel with water and lava. There's many so I'd audit them all.

Might be an NEI thing

**Comment by Saphrym** [comment]
Was a mod conflict bug.
