### ISSUE TITLE
Cheesecake - Infinite source of food.

### ISSUE THREAD

**Issue by Khaysis** [MentatMinions/IndustriaArcanum#81]
I found a cheesecake from Pam's harvestcraft and was able to place it down multiple times. Will report more once i test the rest of the cakes.

**Comment by Saphrym** [comment]
NEeds to be validated with 1.5.1+

**Comment by Khaysis** [comment]
This is still an issue with new versions of the pack. Server reset may be required to see any changes.

**Comment by Saphrym** [comment]
Seems fixed.
