### ISSUE TITLE
Wooden Axe displays coordinants and will not break blocks.

### ISSUE THREAD

**Issue by Khaysis** [MentatMinions/IndustriaArcanum#86]
Screenshot available on request.

**Comment by Saphrym** [comment]
Wooden axe is the "wand" for WorldEdit which won't be in the final pack. FYI. :) Will keep this open to remind me. Thanks!

**Comment by Saphrym** [comment]
Ok. Removing WorldEdit and replacing with a new one that won't have these kinds of issues.
