### ISSUE TITLE
Generated structure in wrong biome

### ISSUE THREAD

**Issue by itanshi** [MentatMinions/IndustriaArcanum#87]
![2015-01-20_05 24 25](https://cloud.githubusercontent.com/assets/373669/5816464/1c6c7074-a066-11e4-854e-a3353eedef11.png)

**Comment by itanshi** [comment]
Also, the shape is going to do this sometimes 
![2015-01-20_05 36 50](https://cloud.githubusercontent.com/assets/373669/5816516/84a7b05e-a066-11e4-8854-db4d4fc6d85c.png)

**Comment by Saphrym** [comment]
Yep. Working on these.

**Comment by Saphrym** [comment]
New structure mod is working much better. We'll know more after exploration.
