### ISSUE TITLE
Peanut seeds are unobtainable. Grass drops are off for Pam's Harvestcraft.

### ISSUE THREAD

**Issue by Khaysis** [MentatMinions/IndustriaArcanum#88]
Resolved. Peanuts can be found in pregenerated Gazebos. Rare but obtainable.

**Comment by Saphrym** [comment]
Check the Pam's Gardens. She changed the way the food is generated. It's now small one-block gardens that if you break them, you get multiple crops.

**Comment by Khaysis** [comment]
Yeah I found it under ground garden. I'm just not sure which biomes it spawns in.

**Comment by Khaysis** [comment]
I was able to find 1 Ground garden in an extreme hills biome in a pregenerated structure.
They are there, It's just Very hard to find.

**Comment by Khaysis** [comment]
Never mind  They are in the small garden shacks that have growth lanterns in them. They are as rare as they need to be.

**Comment by Saphrym** [comment]
Ok.
