### ISSUE TITLE
Flaxbeard's Esteemed Innovation Shift click on a Nether Crucible crashes client.

### ISSUE THREAD

**Issue by Khaysis** [MentatMinions/IndustriaArcanum#89]
The Flaxbeard's Esteemed Innovation book can look up block contained with in the mod. When doing so with the Nether Crucible, the minecraft client crashes and throws a Java.exception error when trying to log back into the server until restart.

**Comment by Saphrym** [comment]
Removing Flaxbeard's for lack of support and updating. I hate doing this... but the mod seems to be abandoned at this point.
