### ISSUE TITLE
Ore Generation - Railcraft and Apples&Milk&Tea! recipes require lead, copper, and tin.

### ISSUE THREAD

**Issue by Khaysis** [MentatMinions/IndustriaArcanum#90]

**Comment by Khaysis** [comment]
Might be easier to change recipes to use vanilla ores.

**Comment by Khaysis** [comment]
With the addition of Forestry in 1.6.0 the need for copper and tin has increased.

**Comment by Khaysis** [comment]
Clockwork Phase can also use lead, copper, tin, and bronze. All of which are added by Forestry.

**Comment by Saphrym** [comment]
Seems the ore is fine after world reset.
